// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Application.Views.ImportView = (function(_super) {

    __extends(ImportView, _super);

    function ImportView() {
      return ImportView.__super__.constructor.apply(this, arguments);
    }

    ImportView.prototype.el = '#main';

    ImportView.prototype.template = $('#import_template').html();

    ImportView.prototype.render = function() {
      var compiled;
      compiled = _.template(this.template);
      return this.$el.html(compiled());
    };

    return ImportView;

  })(Backbone.View);

}).call(this);
