// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Application.Views.IndexView = (function(_super) {

    __extends(IndexView, _super);

    function IndexView() {
      this.render = __bind(this.render, this);
      return IndexView.__super__.constructor.apply(this, arguments);
    }

    IndexView.prototype.template = $('#index_template').html();

    IndexView.prototype.el = '#main';

    IndexView.prototype.events = {
      "click #add_dataset": "addDataset"
    };

    IndexView.prototype.render = function() {
      this.$el.html(this.template);
      return this.collection.forEach(function(dataset) {
        var view;
        view = new Application.Views.DatasetView({
          model: dataset
        });
        return view.render();
      });
    };

    IndexView.prototype.addDataset = function() {
      return this.collection.add(new Application.Models.Dataset());
    };

    IndexView.prototype.initialize = function() {
      this.collection.on('add', this.render);
      if (this.collection.size() === 0) {
        return this.addDataset();
      }
    };

    return IndexView;

  })(Backbone.View);

}).call(this);
