// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Application.Models.Field = (function(_super) {

    __extends(Field, _super);

    function Field() {
      return Field.__super__.constructor.apply(this, arguments);
    }

    Field.prototype.defaults = {
      definition: "",
      json: "",
      name: "",
      rdfa: "",
      type: "text",
      value: ""
    };

    return Field;

  })(Backbone.Model);

  Application.Collections.Fields = (function(_super) {

    __extends(Fields, _super);

    function Fields() {
      return Fields.__super__.constructor.apply(this, arguments);
    }

    Fields.prototype.model = Application.Models.Field;

    return Fields;

  })(Backbone.Collection);

}).call(this);
