---
basic:
  - name: Title
    definition: Human-readable name
    json: title
    rdfa: dct:title

  - name: Description
    definition: Human-readable description
    json: description
    rdfa: dct:description

  - name: Tags
    definition: Keywords describing tags
    json: keyword
    rdfa: dcat:keyword
    type: text

  - name: Last Update
    definition: Most recent date modified
    json: modified
    rdfa: dcterms:modified

  - name: Publisher
    definition: The publishing agency
    json: publisher
    rdfa: foaf:Organization

  - name: Contact Name
    definition: "First, last"
    json: person
    rdfa: foaf:Person

  - name: Contact Email
    definition: Contact person's email
    json: mbox
    rdfa: foaf:mbox

  - name: Unique Identifier
    definition: A unique identifier for the dataset
    json: identifier
    rdfa: dcterms:identifier

  - name: Public Access Level
    definition: Whether the dataset is public
    json: accessLevel
    rdfa: xsd:boolean

  - name: Data Dictionary
    definition: URL to documentation
    json: dataDictionary
    rdfa: dcat:dataDictionary
    type: url

  - name: Download URL
    definition: URL to dataset 
    json: accessURL
    rdfa: dcat:download
    type: url

  - name: Endpoint
    definition: API Endpoint
    json: webService
    rdfa: dcat:webService
    type: url

  - name: Format
    definition: File format or API type
    json: format
    rdfa: dcterms:format

  - name: License
    definition: The license dataset is published with
    json: license
    rdfa: dcterms:license

  - name: Spatial
    definition: Range of spatial applicability
    json: spatial
    rdfa: dcterms:spatial

  - name: Temporal
    definition: Range of temporal applicability
    json: temporal
    rdfa: dcterms:temporal

expanded:

  - name: Release Date
    definition: Date of issuance
    json: issued
    rdfa: dct:issued

  - name: Frequency
    definition: Frequency of update
    json: accrualPeriodicity
    rdfa: dct:accrualPeriodocity

  - name: Language
    definition: Language of the dataset
    json: language
    rdfa: dcat:language

  - name: Granularity
    definition: Level of granularity of dataset
    json: granularity
    rdfa: dcat:granularity

  - name: Data Quality
    definition: The quality of data
    json: dataQuality
    rdfa: dcat:dataQuality

  - name: Category
    definition: Main thematic category
    json: theme
    rdfa: dcat:theme

  - name: Related Documents
    definition: Related material
    json: references
    rdfa: dcat:distribution

  - name: Size
    definition: Size of the downloadable dataset
    json: size
    rdfa: dcat:size

  - name: Homepage URL
    definition: Dataset homepage
    json: landingPage
    rdfa: foaf:homepage
    type: url

  - name: RSS Feed
    definition: URL for RSS feed of data
    json: feed
    rdfa: dcat:feed
    type: url

  - name: System of Records
    definition: URL to the System of Records for this dataset
    json: systemOfRecords
    rdfa: dcat:distribution
    type: url




