// Generated by CoffeeScript 1.4.0
(function() {
  var importSchema;

  importSchema = (function() {

    importSchema.prototype.data = $('#schema').html();

    importSchema.prototype.basic = new Application.Collections.Fields();

    importSchema.prototype.extended = new Application.Collections.Fields();

    function importSchema() {
      this.schema = jsyaml.load(this.data);
      this["import"]('basic', this.schema.basic);
    }

    importSchema.prototype["import"] = function(type, fields) {
      var _this = this;
      return $.each(fields, function(k, field) {
        var model;
        model = new Application.Models.Field(field);
        return _this[type].add(model);
      });
    };

    return importSchema;

  })();

  Application.Schema = new importSchema();

}).call(this);
